# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2048M
org.gradle.parallel=true

java_version=25

# Minecraft properties
minecraft_version=26.1

# Mod properties
archives_name=locator-border
maven_group=me.liqw
enabled_platforms=fabric,neoforge
mod_version=1.2.2

# Dependencies
fabric_loader_version=0.18.5
fabric_api_version=0.144.3+26.1
neoforge_version=26.1.0.8-beta
cloth_config_version=26.1.154
modmenu_version=18.0.0-alpha.8