modLoader="javafml"
loaderVersion="[1,)"

issueTrackerUrl = "${issues}"
license = "MIT"

[[mods]]
displayName = "Locator Border"
modId = "locator_border"
description = "${description}"
version = "${version}"
authors = "liqw"

logoFile = "assets/locator-border/icon.png"

[[mixings]]
config = "locator-border.mixins.json"

[[dependencies.locator_border]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "CLIENT"